### ISSUE TITLE
监听一段时间会断线

### ISSUE THREAD

**Issue by LHopitalJ** [flxxyz/douyudm#44]
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (D:\wwwroot\douyudm-master\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (D:\wwwroot\douyudm-master\node_modules\mysql\lib\Connection.js:94:28)
    at Socket.<anonymous> (D:\wwwroot\douyudm-master\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (D:\wwwroot\douyudm-master\node_modules\mysql\lib\Connection.js:423:8)
    at Protocol.emit (events.js:400:28)
    at Protocol._delegateError (D:\wwwroot\douyudm-master\node_modules\mysql\lib\protocol\Protocol.js:398:10)
    at Protocol.end (D:\wwwroot\douyudm-master\node_modules\mysql\lib\protocol\Protocol.js:116:8)
    at Socket.<anonymous> (D:\wwwroot\douyudm-master\node_modules\mysql\lib\Connection.js:94:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}

**Comment by flxxyz** [comment]
...你这应该不是类库提供的功能，并没有mysql的相关支持，这个 `events.js` 很明显也不是本项目里的，比较可能就是你加入了 `mysql` 支持，并且 `mysql` 断开了链接
